name: Build And Release

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  test:
    name: build project
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Get version
      id: get_version
      shell: bash
      run: |
        echo "using version tag ${GITHUB_REF:10}"
        echo ::set-output name=version::"${GITHUB_REF:10}"

    - name: build_windows
      run: |
        $ENV:RUSTFLAGS='-C target-feature=+crt-static'
        $ENV:CARGO_BUILD_JOBS="$(nproc)"
        rustup target add x86_64-pc-windows-msvc
        cargo clean
        cargo build --bin client --features client --release
        cargo build --bin server --features server --release
        cargo build --bin cfth --features cfth --release
        Get-ChildItem .\target\release\
      shell: pwsh
        

    - name: before_windows_upload
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        New-Item -ItemType Directory -Force -Path Release
        Get-ChildItem .\target\release\
        Copy-Item .\target\release\server.exe Release\server.exe
        Copy-Item .\target\release\client.exe Release\client.exe
        Copy-Item .\target\release\cfth.exe Release\cfth.exe
      shell: pwsh
    
    - name: Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          Release/server.exe
          Release/client.exe
          Release/cfth.exe
        name: 'Ziafp ${{ steps.get_version.outputs.VERSION }}'